---
version: '3'
services:
    demo_java_webapp_1:
        image: demo_java_webapp_1:newest
        container_name: demo_java_webapp_1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./target/:/usr/local/tomcat/webapps/
        networks:
            - default
