---
version: '3'
services:
    java-web-app1:
        image: java-web-app1:newest
        container_name: java-web-app1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./target/:/usr/local/tomcat/webapps/
        networks:
            - default
